### PR TITLE
Malformed RestMethod responses

### PR DESCRIPTION
**Pull request by eliasericsson**
Malformed RestMethod responses have been changed in the same manner as the invoice module was fixed.

### CODE REVIEW

**Comment by PauloRamosGit** [comment]
Hi @eliasericsson ,

By changing "$obj = @() + $response.Substring(1) | ConvertFrom-Json" to "$obj = @() + $response" you are changing the functions response from "Object[]" to "String". That will break all scripts using this module.

Can you explain further?

Cheers,
Paulo

**Comment by eliasericsson** [comment]
Hi Paulo,

I'm in the wrong here. I thought I had corrected some issues I was having,
but after further investigation my solution was incorrect.

I'm trying to use the Get-PCCustomerLicensesUsage cmdlet, and I get the
following errors:

1.
Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
At
C:\Users\149999eler\PartnerCenterPowerShellModule\PartnerCenterModule\PartnerCenterAnalytics.psm1:83
char:17
+ ... $response = Invoke-RestMethod -Uri $url -Headers $headers -ContentTyp
...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation:
(System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId :
WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand


2.
You cannot call a method on a null-valued expression.
At
C:\Users\149999eler\PartnerCenterPowerShellModule\PartnerCenterModule\PartnerCenterAnalytics.psm1:84
char:5
+     $obj = @() + $response.Substring(1) | ConvertFrom-Json
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull


3.
The property 'TypeNames' cannot be found on this object. Verify that the
property exists.
At
C:\Users\149999eler\PartnerCenterPowerShellModule\PartnerCenterModule\commons.ps1:13
char:4
+    $item.PSObject.TypeNames.Insert(0, $type)
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [],
PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

I thought I solved #2, but I failed to see that it was dependent on #1.

My code is as follows:
1. Import the module
2. Add-PCAuthentication -cspAppID <AppID> -cspDomain <Domain>
-cspClientSecret <Secret as a secure string>
3. Get-PCCustomerLicensesUsage - tenantid <customer tenant id>

My current assumption is that the application needs to be granted some
extra permissions to access this resource:
"
https://api.partnercenter.microsoft.com/v1/customers/{0}/analytics/licenses/deployment"
-f $tenantid

Do you have insight to what may cause this?

Thanks,
Elias Ericsson Rydberg

2017-12-08 23:45 GMT+01:00 Paulo Ramos <notifications@github.com>:

**Comment by PauloRamosGit** [comment]
Hi @eliasericsson ,

Thank you for the follow up and additional details.

I see that you are using app authentication. Have you tried to use user authentication? (This requires the App created during https://msdn.microsoft.com/library/partnercenter/mt709136.aspx process to be Native App instead of Web App)

$credentials = Get-Credential '<username@domain>'
Add-PCAuthentication -cspappID '<native app id GUID>' -cspDomain '<csp partner domain>' -credential $credentials

The reason for this is that in some methods of Partner Center API user auth is required.

**Comment by PauloRamosGit** [comment]
Close due to inactivity

**Pull request closed without merging**
