### PR TITLE
Add Remove-PCCustomerRelationship function

### PR DESCRIPTION
**Pull request by cblackuk**
# Description

This will address the inability to automate off-boarding of customers as this function will remove reseller relationship based on the API guide https://docs.microsoft.com/en-us/partner-center/develop/remove-a-reseller-relationship-with-a-customer

## Related issue

https://github.com/Microsoft/PartnerCenterPowerShellModule/issues/70

### CODE REVIEW

**Comment by cblackuk** [comment]
Also fixed typo in another function as it had triple C...

**Comment by cblackuk** [comment]
This function allows me to remove a customer from CSP portal to fully automate my Azure Stack off-boarding

**Comment by joelst** [comment]
Approved. Will update help markdown, exports in the module, and the version information.

**Comment by cblackuk** [comment]
Any chance we can update the module in PSGallery @joelst please?

**Comment by isaiahwilliams** [comment]
Hi @cblackuk we will be posting an update on the PowerShell gallery by Friday. We are working to incorporate a handful of other updates as well.

**Comment by cblackuk** [comment]
Hi @isaiahwilliams  Thanks a lot! That makes perfect sense :-)

**Pull request merged**
